services:
  app:
    image: class-attend-app:local
    build:
      context: .
      args:
        APP_VERSION: "local"
    ports:
      - "8080:5173"
    volumes:
      - ./data:/app/data
    restart: always
