services:
  app:
    image: class-attend-app:0.0.2
    build:
      context: .
      args:
        APP_VERSION: "0.0.2"
    ports:
      - "8080:5173"
    volumes:
      - ./data:/app/data
    restart: always
